"""
Anesthesia Journal Digest — Email Builder
==========================================
HTML email templates for all three email types.

FONTS ARE STANDARDIZED across every email here. One font family and one size
hierarchy are defined as constants below and reused everywhere so the Monday
digest, Saturday CME, and monthly digest look visually identical element-for-
element (a journal heading is the same size in all three, an article title is the
same size in all three, etc.).
"""

from __future__ import annotations

from datetime import datetime, timedelta

# Specialty branding (BRAND_SHORT leads the subject line, BRAND_FULL is the
# header/footer title). Driven by the active specialty's JSON via config.
from config import (BRAND_SHORT, BRAND_FULL, SPECIALTY_NAME, JOURNAL_COUNT,
                    PODCAST_MINUTES_TARGET as AUDIO_MIN)

# ── Standard typography (shared by ALL emails) ───────────────────────────────
# Web-safe stack so it renders the same in every mail client.
FONT = "Arial, Helvetica, sans-serif"

# One size hierarchy, used consistently across all three email types.
FS_TITLE = 22   # Main email title (the colored header banner)
FS_HEAD  = 17   # Section headings: journal names, "This Week's Articles", etc.
FS_LINK  = 15   # Article titles / primary links / episode titles
FS_BODY  = 14   # Body text, descriptions, abstracts, button labels
FS_META  = 12   # Metadata: dates, authors, impact factor, durations
FS_FOOT  = 11   # Footer, disclaimers, small badges

LH = "1.45"     # Readable line-height for body copy (mobile-friendly)


def build_digest_email(articles: list, podcasts: list, bonus_podcasts: list,
                       has_audio: bool = False,
                       podcast_url: str | None = None,
                       deepdive_url: str | None = None,
                       summaries: list | None = None,
                       audio_attached: bool = False) -> tuple[str, str]:
    """Build Monday/Thursday digest email. Returns (subject, html).

    Audio is delivered one of two ways:
      - ``podcast_url`` set → a clickable card linking to the hosted player.
      - ``audio_attached`` True → a banner noting the MP3 is attached to the email.
    """
    today = datetime.now()
    # Map article URL -> its Deep Dive summary, so each article can carry a
    # one-line "bottom line" teaser + a "Read more" anchor to the summaries page.
    summary_by_url = {s.get("url"): s for s in (summaries or []) if s.get("url")}
    day_name = today.strftime("%A")
    date_str = today.strftime("%B %d, %Y")

    subject = f"{BRAND_SHORT} Digest — {day_name}, {today.strftime('%b %d')}"

    # Group articles by journal, sorted by impact factor
    by_journal = {}
    for a in articles:
        key = a["journal_abbr"]
        if key not in by_journal:
            by_journal[key] = {"name": a["journal"], "abbr": key,
                               "if": a["impact_factor"], "articles": []}
        by_journal[key]["articles"].append(a)
    sorted_j = sorted(by_journal.values(), key=lambda j: j["if"], reverse=True)

    total = len(articles)
    oa_count = sum(1 for a in articles if a["is_open_access"])

    # Audio summary card (API mode only). The episode is hosted on GitHub Pages
    # and played inline there, so the whole card is a clickable, cover-art-style
    # "play" tile that links to the player page.
    audio_banner = ""
    if has_audio and podcast_url:
        audio_banner = f"""
    <tr><td style="padding:18px 20px 6px;">
      <a href="{podcast_url}" style="text-decoration:none;display:block;">
      <table width="100%" cellpadding="0" cellspacing="0" style="background:linear-gradient(135deg,#0e2a3b,#1a5276);border-radius:12px;overflow:hidden;">
        <tr>
          <td width="108" valign="middle" align="center" style="padding:20px 0 20px 18px;">
            <div style="width:84px;height:84px;border-radius:14px;background:linear-gradient(135deg,#1a5276,#2e86c1);text-align:center;line-height:84px;font-size:38px;color:#ffffff;box-shadow:0 4px 14px rgba(0,0,0,0.35);">&#127911;</div>
          </td>
          <td style="padding:18px 20px;">
            <div style="font-family:{FONT};font-size:{FS_HEAD}px;font-weight:bold;color:#ffffff;line-height:1.3;">&#127911; {BRAND_SHORT} Digest Audio Summary — {date_str}</div>
            <div style="font-family:{FONT};font-size:{FS_BODY}px;color:#cfe3f2;margin-top:6px;line-height:{LH};">A ~{AUDIO_MIN} minute AI-generated two-host discussion of today's journal highlights</div>
            <div style="margin-top:12px;">
              <span style="display:inline-block;background:#2e86c1;color:#ffffff;font-family:{FONT};font-size:{FS_BODY}px;font-weight:bold;padding:8px 18px;border-radius:22px;">&#9654; Play episode</span>
            </div>
            <div style="font-family:{FONT};font-size:{FS_FOOT}px;color:#7fa3bd;margin-top:12px;font-style:italic;line-height:{LH};">This audio was generated by AI (Claude + Edge TTS) and is not affiliated with any journal.</div>
          </td>
        </tr>
      </table>
      </a>
    </td></tr>"""
    elif has_audio and audio_attached:
        # Audio is attached to the email as an MP3 (no hosted player page).
        audio_banner = f"""
    <tr><td style="padding:18px 20px 6px;">
      <table width="100%" cellpadding="0" cellspacing="0" style="background:linear-gradient(135deg,#0e2a3b,#1a5276);border-radius:12px;overflow:hidden;">
        <tr>
          <td width="108" valign="middle" align="center" style="padding:20px 0 20px 18px;">
            <div style="width:84px;height:84px;border-radius:14px;background:linear-gradient(135deg,#1a5276,#2e86c1);text-align:center;line-height:84px;font-size:38px;color:#ffffff;box-shadow:0 4px 14px rgba(0,0,0,0.35);">&#127911;</div>
          </td>
          <td style="padding:18px 20px;">
            <div style="font-family:{FONT};font-size:{FS_HEAD}px;font-weight:bold;color:#ffffff;line-height:1.3;">&#127911; AI Audio Summary attached — ~{AUDIO_MIN} min podcast</div>
            <div style="font-family:{FONT};font-size:{FS_BODY}px;color:#cfe3f2;margin-top:6px;line-height:{LH};">A two-host discussion covering today's highlights is attached to this email as an MP3 — download and listen on the go.</div>
            <div style="font-family:{FONT};font-size:{FS_FOOT}px;color:#7fa3bd;margin-top:12px;font-style:italic;line-height:{LH};">This audio was generated by AI (Claude + Edge TTS) and is not affiliated with any journal.</div>
          </td>
        </tr>
      </table>
    </td></tr>"""

    # Deep Dive button — sits directly below the podcast card and links to the
    # GitHub Pages summaries page (green, to distinguish it from the audio card).
    deepdive_banner = ""
    if deepdive_url:
        deepdive_banner = f"""
    <tr><td style="padding:8px 20px 6px;">
      <a href="{deepdive_url}" style="text-decoration:none;display:block;">
      <table width="100%" cellpadding="0" cellspacing="0" style="background:linear-gradient(135deg,#13321f,#1e8449);border-radius:12px;overflow:hidden;">
        <tr>
          <td width="108" valign="middle" align="center" style="padding:18px 0 18px 18px;">
            <div style="width:84px;height:84px;border-radius:14px;background:linear-gradient(135deg,#1e8449,#27ae60);text-align:center;line-height:84px;font-size:38px;color:#ffffff;box-shadow:0 4px 14px rgba(0,0,0,0.35);">&#128214;</div>
          </td>
          <td style="padding:18px 20px;">
            <div style="font-family:{FONT};font-size:{FS_HEAD}px;font-weight:bold;color:#ffffff;line-height:1.3;">&#128214; Read the Deep Dive</div>
            <div style="font-family:{FONT};font-size:{FS_BODY}px;color:#d6f0e0;margin-top:6px;line-height:{LH};">Structured summaries of every featured article — what they did, design, findings, meaning, why it matters, limitations</div>
            <div style="margin-top:12px;">
              <span style="display:inline-block;background:#27ae60;color:#ffffff;font-family:{FONT};font-size:{FS_BODY}px;font-weight:bold;padding:8px 18px;border-radius:22px;">Open summaries &#8594;</span>
            </div>
          </td>
        </tr>
      </table>
      </a>
    </td></tr>"""

    # Articles
    articles_html = ""
    for j in sorted_j:
        articles_html += f"""
    <tr><td style="padding:18px 20px 6px 20px;">
        <h2 style="margin:0;font-family:{FONT};font-size:{FS_HEAD}px;color:#1a5276;">
            {j['name']}
            <span style="font-family:{FONT};font-size:{FS_META}px;color:#999;font-weight:normal;">
                IF {j['if']}
            </span>
        </h2>
    </td></tr>"""
        for art in j["articles"]:
            oa = f' <span style="background:#27ae60;color:#fff;padding:1px 6px;border-radius:3px;font-family:{FONT};font-size:{FS_FOOT}px;font-weight:bold;">OPEN ACCESS</span>' if art["is_open_access"] else ""
            auth = f'<div style="font-family:{FONT};font-size:{FS_META}px;color:#777;margin-top:2px;">{art["authors"]}</div>' if art["authors"] else ""

            # Abstracts are intentionally NOT shown — the reader follows the title
            # link for full text; the AI "Bottom line" below is the digest value-add.

            # Deep Dive "bottom line" teaser + Read more anchor (if we have a
            # summary for this article and a page to link to).
            bl_html = ""
            s = summary_by_url.get(art["url"])
            if s and s.get("bottom_line"):
                more = ""
                if deepdive_url:
                    anchor = s.get("anchor", "")
                    more = (f' <a href="{deepdive_url}#{anchor}" style="font-family:{FONT};'
                            f'color:#2e86c1;text-decoration:none;font-weight:bold;white-space:nowrap;">'
                            f'Read more &#8594;</a>')
                bl_html = (f'<div style="font-family:{FONT};font-size:{FS_BODY}px;color:#33444f;'
                           f'margin-top:8px;line-height:{LH};padding:10px 12px;background:#eef6fb;'
                           f'border-left:3px solid #2e86c1;border-radius:0 6px 6px 0;">'
                           f'<strong style="color:#1a5276;">Bottom line:</strong> '
                           f'{s["bottom_line"]}{more}</div>')

            articles_html += f"""
    <tr><td style="padding:4px 20px 12px 30px;">
        <a href="{art['url']}" style="font-family:{FONT};color:#2c3e50;text-decoration:none;font-size:{FS_LINK}px;line-height:{LH};font-weight:600;">{art['title']}</a>{oa}
        {auth}
        <div style="font-family:{FONT};font-size:{FS_META}px;color:#999;margin-top:2px;">{art['date_str']}</div>
        {bl_html}
    </td></tr>"""

    if not articles:
        articles_html = f'<tr><td style="padding:20px;font-family:{FONT};font-size:{FS_BODY}px;color:#999;font-style:italic;">No new articles since the last digest. This can happen between journal issues.</td></tr>'

    # Podcasts — rendered as cards with a styled "Listen" button.
    pods_html = ""
    all_pods = podcasts + bonus_podcasts
    if all_pods:
        pods_html = f'<tr><td style="padding:18px 20px 6px;"><h2 style="margin:0;font-family:{FONT};font-size:{FS_HEAD}px;color:#1a5276;">🎧 Journal Podcast Episodes</h2></td></tr>'
        for ep in all_pods:
            jrnl = f" · {ep['journal_abbr']}" if ep.get('journal_abbr') else ""
            meta_bits = []
            if ep.get('date_str'):
                meta_bits.append(ep['date_str'])
            if ep.get('duration'):
                meta_bits.append(str(ep['duration']))
            meta = " · ".join(meta_bits)
            meta_html = f'<div style="font-family:{FONT};font-size:{FS_META}px;color:#999;margin-top:6px;">{meta}</div>' if meta else ""
            pods_html += f"""
    <tr><td style="padding:6px 20px;">
      <table width="100%" cellpadding="0" cellspacing="0" style="border:1px solid #e3e8ee;border-radius:8px;background:#fbfcfd;">
        <tr>
          <td width="58" valign="top" style="padding:14px 0 14px 14px;">
            <div style="width:40px;height:40px;border-radius:8px;background:#1a5276;text-align:center;font-size:18px;line-height:40px;">&#127908;</div>
          </td>
          <td valign="top" style="padding:13px 8px 13px 12px;">
            <div style="font-family:{FONT};font-size:{FS_META}px;font-weight:bold;color:#1a5276;">{ep['podcast_name']}{jrnl}</div>
            <div style="font-family:{FONT};font-size:{FS_LINK}px;color:#2c3e50;margin-top:3px;line-height:{LH};font-weight:600;">{ep['title']}</div>
            {meta_html}
          </td>
          <td width="96" valign="middle" align="right" style="padding:13px 14px;">
            <a href="{ep['url']}" style="display:inline-block;background:#2e86c1;color:#ffffff;text-decoration:none;font-family:{FONT};font-size:{FS_BODY}px;font-weight:bold;padding:9px 16px;border-radius:20px;white-space:nowrap;">&#9654; Listen</a>
          </td>
        </tr>
      </table>
    </td></tr>"""

    html = _wrap(f"""
    <tr><td style="background:linear-gradient(135deg,#1a5276,#2e86c1);padding:24px 20px;text-align:center;">
        <h1 style="margin:0;font-family:{FONT};color:#fff;font-size:{FS_TITLE}px;">{BRAND_FULL}</h1>
        <p style="margin:6px 0 0;font-family:{FONT};color:rgba(255,255,255,0.8);font-size:{FS_META}px;">{date_str} · {total} articles · {oa_count} open access</p>
    </td></tr>
    {audio_banner}
    {deepdive_banner}
    {articles_html}
    <tr><td style="padding:8px 20px;"><hr style="border:none;border-top:1px solid #eee;"></td></tr>
    {pods_html}""")

    return subject, html


def build_saturday_email(articles_this_week: list,
                         cme_questions: list | None = None,
                         quiz_url: str | None = None,
                         deepdive_url: str | None = None) -> tuple[str, str]:
    """Build Saturday CME email. Returns (subject, html)."""
    today = datetime.now()
    week_start = today - timedelta(days=today.weekday())
    date_str = today.strftime("%B %d, %Y")

    subject = f"{BRAND_SHORT} Weekly Review & Self-Assessment — {today.strftime('%b %d')}"

    # Prominent call-to-action linking to the interactive quiz + certificate.
    quiz_cta = ""
    if quiz_url:
        quiz_cta = f"""
    <tr><td style="padding:18px 20px 4px;">
      <table width="100%" cellpadding="0" cellspacing="0" style="background:linear-gradient(135deg,#1a5276,#2e86c1);border-radius:12px;">
        <tr><td style="padding:22px 22px;text-align:center;">
          <div style="font-family:{FONT};font-size:{FS_HEAD}px;font-weight:bold;color:#ffffff;">&#127891; Take this week's self-assessment</div>
          <div style="font-family:{FONT};font-size:{FS_BODY}px;color:#cfe3f2;margin:8px 0 16px;line-height:{LH};">10 single-best-answer questions · instant score &amp; explanations · downloadable completion record</div>
          <a href="{quiz_url}" style="display:inline-block;background:#ffffff;color:#1a5276;text-decoration:none;font-family:{FONT};font-size:{FS_BODY}px;font-weight:bold;padding:14px 28px;border-radius:24px;">Take the Self-Assessment &amp; Get Certificate &#8594;</a>
        </td></tr>
      </table>
    </td></tr>"""

    # Week's highlights
    highlights = ""
    if articles_this_week:
        top = sorted(articles_this_week, key=lambda a: a["impact_factor"], reverse=True)[:10]
        highlights = f"""
    <tr><td style="padding:18px 20px 6px;">
        <h2 style="margin:0;font-family:{FONT};font-size:{FS_HEAD}px;color:#1a5276;">📋 This Week's Articles</h2>
        <p style="font-family:{FONT};font-size:{FS_BODY}px;color:#999;margin:5px 0 0;">This week's self-assessment is based on these articles</p>
    </td></tr>"""
        for i, art in enumerate(top, 1):
            oa = f' <span style="background:#27ae60;color:#fff;padding:1px 6px;border-radius:3px;font-family:{FONT};font-size:{FS_FOOT}px;">OA</span>' if art["is_open_access"] else ""
            highlights += f"""
    <tr><td style="padding:4px 20px 8px 30px;">
        <strong style="font-family:{FONT};font-size:{FS_LINK}px;color:#999;">{i}.</strong>
        <a href="{art['url']}" style="font-family:{FONT};font-size:{FS_LINK}px;color:#2c3e50;text-decoration:none;font-weight:600;line-height:{LH};">{art['title']}</a>{oa}
        <div style="font-family:{FONT};font-size:{FS_META}px;color:#999;">{art['journal_abbr']} · {art['date_str']}</div>
    </td></tr>"""

    # Normally the questions live only on the published quiz page and the email
    # just links to it. When a specialty does NOT publish a quiz page (quiz_url
    # is None) but DID generate questions, render them inline so the email is
    # self-contained (e.g. EP, which launches without GitHub Pages publishing).
    questions_html = ""
    if cme_questions and not quiz_url:
        questions_html = _inline_questions_html(cme_questions)

    # Deep Dive reminder — a PROMINENT banner ABOVE the quiz, linking to the SAME
    # summaries page published Monday. Nudges the reader to study first.
    deepdive_ref = ""
    if deepdive_url:
        deepdive_ref = f"""
    <tr><td style="padding:18px 20px 4px;">
      <a href="{deepdive_url}" style="text-decoration:none;display:block;">
      <table width="100%" cellpadding="0" cellspacing="0" style="background:linear-gradient(135deg,#13321f,#1e8449);border-radius:12px;overflow:hidden;">
        <tr>
          <td width="96" valign="middle" align="center" style="padding:20px 0 20px 18px;">
            <div style="width:72px;height:72px;border-radius:14px;background:linear-gradient(135deg,#1e8449,#27ae60);text-align:center;line-height:72px;font-size:34px;color:#ffffff;box-shadow:0 4px 14px rgba(0,0,0,0.35);">&#128214;</div>
          </td>
          <td style="padding:18px 20px;">
            <div style="font-family:{FONT};font-size:{FS_HEAD}px;font-weight:bold;color:#ffffff;line-height:1.3;">&#128214; Read the Deep Dive first</div>
            <div style="font-family:{FONT};font-size:{FS_BODY}px;color:#d6f0e0;margin-top:6px;line-height:{LH};">This quiz is based on the structured summaries of this week's articles. If you haven't read them yet, do so now — then the questions will be straightforward.</div>
            <div style="margin-top:12px;">
              <span style="display:inline-block;background:#27ae60;color:#ffffff;font-family:{FONT};font-size:{FS_BODY}px;font-weight:bold;padding:9px 20px;border-radius:22px;">Open the summaries &#8594;</span>
            </div>
          </td>
        </tr>
      </table>
      </a>
    </td></tr>"""

    # MOC reminder
    moc_html = f"""
    <tr><td style="padding:8px 20px;"><hr style="border:none;border-top:1px solid #eee;"></td></tr>
    <tr><td style="padding:16px 20px;background:#f8f9fa;">
        <strong style="font-family:{FONT};color:#1a5276;font-size:{FS_HEAD}px;">📊 Self-Assessment Tracker</strong>
        <p style="font-family:{FONT};font-size:{FS_BODY}px;color:#555;margin:7px 0 0;line-height:{LH};">
            Your self-assessment tracker is updated monthly. Time you spend reading and
            reflecting on these articles may be eligible for self-reporting under
            <strong>RCPSC MOC Section&nbsp;2 (Self-Learning)</strong> — you are responsible
            for confirming your own eligibility.
        </p>
    </td></tr>"""

    html = _wrap(f"""
    <tr><td style="background:linear-gradient(135deg,#1a5276,#148f77);padding:24px 20px;text-align:center;">
        <h1 style="margin:0;font-family:{FONT};color:#fff;font-size:{FS_TITLE}px;">Weekly Review & Self-Assessment</h1>
        <p style="margin:7px 0 0;font-family:{FONT};color:rgba(255,255,255,0.85);font-size:{FS_META}px;">{date_str} · Week of {week_start.strftime('%b %d')}</p>
    </td></tr>
    {highlights}
    {deepdive_ref}
    {quiz_cta}
    {questions_html}
    {moc_html}""")

    return subject, html


def _inline_questions_html(questions: list) -> str:
    """Render CME questions (stem, 4 options, answer + rationale, source) inline
    in the email. Used when no published quiz page is available."""
    if not questions:
        return ""
    parts = [f"""
    <tr><td style="padding:18px 20px 4px;">
        <h2 style="margin:0;font-family:{FONT};font-size:{FS_HEAD}px;color:#1a5276;">📝 This Week's Self-Assessment ({len(questions)} questions)</h2>
        <p style="font-family:{FONT};font-size:{FS_META}px;color:#999;margin:5px 0 0;">Single best answer. Correct answers and explanations follow each question.</p>
    </td></tr>"""]
    for i, q in enumerate(questions, 1):
        opts = q.get("options") or {}
        correct = q.get("correct", "")
        opts_html = ""
        for letter in ["A", "B", "C", "D"]:
            if letter not in opts:
                continue
            opts_html += (
                f'<div style="font-family:{FONT};font-size:{FS_BODY}px;color:#2c3e50;'
                f'line-height:{LH};margin:2px 0;"><strong>{letter}.</strong> '
                f'{opts[letter]}</div>')
        correct_text = opts.get(correct, "")
        src = q.get("source_article", "")
        src_url = q.get("source_url", "")
        src_journal = q.get("source_journal", "")
        src_line = ""
        if src:
            link = f'<a href="{src_url}" style="color:#1a5276;text-decoration:none;">{src}</a>' if src_url else src
            src_line = (f'<div style="font-family:{FONT};font-size:{FS_FOOT}px;'
                        f'color:#999;margin-top:8px;">Source: {src_journal} · {link}</div>')
        parts.append(f"""
    <tr><td style="padding:10px 20px;">
      <table width="100%" cellpadding="0" cellspacing="0" style="background:#f8f9fa;border-radius:10px;border:1px solid #eee;">
        <tr><td style="padding:16px 18px;">
          <div style="font-family:{FONT};font-size:{FS_LINK}px;color:#1a5276;font-weight:bold;line-height:{LH};">Question {i}</div>
          <div style="font-family:{FONT};font-size:{FS_BODY}px;color:#2c3e50;line-height:{LH};margin:6px 0 10px;">{q.get('question','')}</div>
          {opts_html}
          <div style="margin-top:12px;padding:12px 14px;background:#eafaf1;border-left:4px solid #27ae60;border-radius:6px;">
            <div style="font-family:{FONT};font-size:{FS_BODY}px;color:#1e8449;font-weight:bold;">Correct answer: {correct}. {correct_text}</div>
            <div style="font-family:{FONT};font-size:{FS_BODY}px;color:#555;line-height:{LH};margin-top:6px;">{q.get('rationale','')}</div>
            {src_line}
          </div>
        </td></tr>
      </table>
    </td></tr>""")
    return "".join(parts)


def build_monthly_email(articles: list, top5: list) -> tuple[str, str]:
    """Build 1st-of-month email with top 5 and MOC tracker attached."""
    today = datetime.now()
    subject = f"{BRAND_SHORT} Monthly Digest & Self-Assessment Tracker — {today.strftime('%B %Y')}"

    top5_html = ""
    for i, art in enumerate(top5, 1):
        oa = " (Open Access)" if art["is_open_access"] else ""
        # Abstracts intentionally omitted — the title links to full text.
        top5_html += f"""
    <tr><td style="padding:6px 20px 14px 30px;">
        <strong style="font-family:{FONT};font-size:{FS_LINK}px;color:#999;">{i}.</strong>
        <a href="{art['url']}" style="font-family:{FONT};color:#2c3e50;text-decoration:none;font-weight:600;font-size:{FS_LINK}px;line-height:{LH};">{art['title']}</a>
        <div style="font-family:{FONT};font-size:{FS_META}px;color:#999;margin-top:2px;">{art['journal_abbr']} · IF {art['impact_factor']}{oa}</div>
    </td></tr>"""

    html = _wrap(f"""
    <tr><td style="background:linear-gradient(135deg,#1a5276,#7d3c98);padding:24px 20px;text-align:center;">
        <h1 style="margin:0;font-family:{FONT};color:#fff;font-size:{FS_TITLE}px;">Monthly Digest & Self-Assessment Tracker</h1>
        <p style="margin:6px 0 0;font-family:{FONT};color:rgba(255,255,255,0.8);font-size:{FS_META}px;">{today.strftime('%B %Y')} · {len(articles)} articles published across 10 journals</p>
    </td></tr>
    <tr><td style="padding:18px 20px 6px;">
        <h2 style="margin:0;font-family:{FONT};font-size:{FS_HEAD}px;color:#1a5276;">Top 5 Articles This Month</h2>
        <p style="font-family:{FONT};font-size:{FS_META}px;color:#999;margin:5px 0 0;">Ranked by impact factor, open access prioritized</p>
    </td></tr>
    {top5_html}
    <tr><td style="padding:16px 20px;background:#f8f9fa;font-family:{FONT};font-size:{FS_BODY}px;color:#555;line-height:{LH};">
        Your Self-Assessment Tracker is attached with this month's entries pre-filled.
        Fill in your <strong>Hours</strong> and <strong>Credits (self-reported)</strong> for articles you actually read.
    </td></tr>""")

    return subject, html


def _wrap(content: str) -> str:
    """Wrap content in the standard email shell, then apply the specialty brand
    pass (swaps the canonical accent colour for the active specialty's)."""
    from branding import brandize
    html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head>
<body style="margin:0;padding:0;background:#f5f6fa;font-family:{FONT};">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#f5f6fa;padding:20px 0;">
<tr><td align="center">
<table width="600" cellpadding="0" cellspacing="0" style="background:#fff;border-radius:8px;box-shadow:0 2px 8px rgba(0,0,0,0.06);overflow:hidden;max-width:600px;width:100%;">
    {content}
    <tr><td style="padding:16px;text-align:center;font-family:{FONT};font-size:{FS_FOOT}px;color:#bbb;background:#f8f9fa;">
        {BRAND_FULL} · Automated via GitHub Actions<br>
        Covering {JOURNAL_COUNT} leading {SPECIALTY_NAME.lower()} journals
    </td></tr>
</table></td></tr></table>
</body></html>"""
    return brandize(html)
